#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model DDVFeedbackLinearization
 Dymola Version 2024x, 2023-10-06 translated this at Fri Sep 27 19:02:11 2024

   */

#include <matrixop.h>
#include "matrixop.c"
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    0
#define NX2_   0
#define NU_    3
#define NY_    2
#define NW_    0
#define NWP_   0
#define NP_    1
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ -1253903006
#define NHash2_ -1448447805
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    0
#define SizePre_ 0
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 3
#define NGlobalHelpI_ 0
#define NSparse_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="DDVFeedbackLinearization";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=0;
#include <dsblock1.c>

/* Define variable names. */

#define Sections_
#define DIRECT_FEED_THROUGH 1

TranslatedEquations
InitialSection

InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
InitialSection
InitialStartSection
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

/* Introducing 2 common subexpressions whereof 2 are global used in 0
   expressions */
/* Of the common subexpressions 2 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,0) = cos(DYNX(U_,2));
DYNX(DYNhelp,1) = sin(DYNX(U_,2));
DYNX(Y_,0) = DYNX(U_,0)*DYNX(DYNhelp,0)+DYNX(U_,1)*DYNX(DYNhelp,1);

/* Introducing 3 common subexpressions whereof 3 are global used in 0
   expressions */
/* Of the common subexpressions 3 are reals, 0 are integers, and 0
   are booleans. */
if (NewParameters_) {
DYNX(DYNhelp,2) = divinvGuarded(DYNX(DP_,0),"epsilon");
}
DYNX(Y_,1) = DYNX(DYNhelp,2)*(DYNX(DYNhelp,0)*DYNX(U_,1)-DYNX(DYNhelp,1)*
  DYNX(U_,0));

DynamicsSection

AcceptedSection1

AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("epsilon", "", 0, 0.25, 0.0,0.0,0.0,0,560)
DeclareInput("vx_P", "[:#(prefix=input)]", 0, 0.0, 0.0,0.0,0.0,0,512)
DeclareInput("vy_P", "[:#(prefix=input)]", 1, 0.0, 0.0,0.0,0.0,0,512)
DeclareInput("theta", "[rad:#(prefix=input)]", 2, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("v_long", "", 0, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("omega", "", 1, 0.0, 0.0,0.0,0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
EndDataBlock
